version: '3.9'

services:
  php-env-insecure:
    build: .
    volumes:
      - ./src:/var/www/html:rw
    ports:
      - 9005:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easyPass123

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9006:80
    environment:
      - PMA_ARBITRARY=1

    