name: Update documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: cd common
      - run: pdoc3 --html --force -o ./docs .
      - run: cd ..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated documentation